#packrat_setup.R
library(packrat)
packrat::init(".")
packrat::on()
packrat::set_opts(local.repos = "./sources/")
install.packages("implyr")
install.packages("devtools")
install.packages(c("shinydashboardPlus","shinydashboard","shinyWidgets","shinycssloaders","shinyjs","DT","shiny","data.table",
                   "glue","tidyverse","readxl"))
devtools::install_version("nloptr", version = "1.0.4", repos = "http://cran.us.r-project.org")
install.packages("lme4")
install.packages("meta")
install.packages(c("DBI", "dplyr", "ggplot2", "beeswarm", "data.table", "dbplyr", "DescTools", "forcats", "furrr", "futile.logger", "future", "gglasso", "glue", "implyr", "jsonlite", "meta", "odbc", "plotly", "purrr", "readr", "rjson", "rlang", "rmeta", "RSQLite", "sparklyr", "stringr", "tibble", "tictoc", "tidyr"))
devtools::install_github("MRCIEU/TwoSampleMR@0.4.26",force = T)
install.packages(c("futile.logger"))
install.packages("RMariaDB",dependencies = T)
install.packages("mockery")
install.packages()
remotes::install_github("kineticadb/RKinetica", force = T)
install.packages("./sources/gtx_2.3.1.tar.gz", repos = NULL, type="source", dependencies = TRUE)
packrat::snapshot()