#ui_fxns.R
guideModalUI <- function(id) {
  ns <- NS(id)
  actionButton(ns("show_guide"), "Show Guide")
}

#' Generate UI for a box containing a radio button selection. The selection choices are updated 
#' by server-side processing
#' @param id Namespace identifier for the module
#' @param box_title (character) A title string to be displayed in the box header
#' @param box_status (character) Predefined Rshiny string determining the colour of the box border and header
#' @param box_solidHeader (logical) Should the box be displayed with a solid header line? 
radio_button_ui <- function(id, box_title = "", box_status = "warning", box_solidHeader = TRUE){
  ns <- NS(id)
  tagList(
    box(width = 12, status = box_status, solidHeader = box_solidHeader, collapsible = T, title = paste0(box_title),
        fluidRow(column(width = 12, radioButtons(ns("buttons"), choices = "", label = "Select which result output to view")))),
    uiOutput(ns("ui_output"))
  )
}

text_input_ui <- function(id,label="") {
  ns <- NS(id)
  textInput(ns("input_text"), label=label)
}

#' Generic helper function to display server-generated UI output
#' @param id Namespace identifier for the module
ui_output_ui <- function(id){
  ns <- NS(id)
  tagList(
    uiOutput(ns("ui_output"))
  )
}

#' UI function which combines a box containing radio buttons with a box containing server-generated UI output.
#' @param id Namespace identifier for the module
radio_with_ui <- function(id){
  ns <- NS(id)
  tagList(
    radio_button_ui(id = ns("radio_buttons"), box_title = "Radio Buttons"),
    ui_output_ui(id = ns("ui_output"))
  )
}

#' Simple UI function for a select input (max_level = 1)
#' @param id Namespace identifier for the module
#' @param choices (character) Vector of possible choices to display
#' @param label (character) Text to display above the selection box
#' @param selected (character) Text selection
single_selectize_ui <- function(id,choices = NULL,label = "",selected = NULL){
  ns <- NS(id)
  tagList(
    selectizeInput(ns("selectize_input"),choices = choices,label = label, selected = selected)
  )
}


output_rg_ui <- function(id){
  ns <- NS(id)
  tagList(
    uiOutput(ns("ui_output"))
  )
}

#' UI for a numeric input
#' @param id Namespace identifier for the module
#' @param label (character) Text to be displayed above the numeric input
#' @param min (numeric) Minimum value for the input
#' @param max (numeric) Maximum value for the input
#' @param value (numeric) Starting value for the input when first rendered
numeric_ui <- function(id, label, min, max, value){
  ns <- NS(id)
  tagList(
    numericInput(inputId = ns("user_input"),
                 label = label,
                 min = min,
                 max = max,
                 value = value)
  )
}

group_selection_rg_ui <- function(id){
  ns <- NS(id)
  tagList(
    selection_average_rg_ui(id = "selection_average_rg", box_title="Selection Category"),
    ui_output_ui(id = ns("ui_output"))
  )
}


selection_average_rg_ui <- function(id, box_title="",box_status = "warning",box_solidHeader=TRUE){
  ns <- NS(id)
  tagList(
    box(width = 12, status = box_status, solidHeader = box_solidHeader, collapsible = T, title = paste0(box_title),
        selectInput("group2",label="Selection",c("MeSH"="mesh","disease"="disease"),selected='disease'),
        sliderInput("rg2","rg_threshold",min=0,max=1,value=0.01),
        sliderInput('pval2','p-value threshold',min=0,max=1,value=0.05),
        actionButton("category", "RUN")
        , type=1)
  )
}

heatmap_table_rg_ui <- function(id,box_title="",box_status = "warning",box_solidHeader=TRUE){
  ns <- NS(id)
  tagList(
    ui_output_ui(id = ns("ui_output"))
  )
}

#' UI ouput for a plot that is generated by server-side processing
#' @param id Namespace identifier for the module
plot_ui <- function(id){
  ns <- NS(id)
  tagList(
    plotOutput(ns("plot"))
  )
}

#' Combined UI for a box containing 2 selection boxes and server-generated plot UI output
#' @param id Namespace identifier for the module
#' @param box_title (character) A title string to be displayed in the box header
#' @param box_status (character) Predefined Rshiny string determining the colour of the box border and header
#' @param box_solidHeader (logical) Should the box be displayed with a solid header line?
#' @param label1 (character) Text to display above the first selection box
#' @param label2 (character) Text to display above the first selection box
plot_with_selection_ui <- function(id, box_title = "", box_status = "warning", box_solidHeader = TRUE, label1 = "", label2 = ""){
  ns <- NS(id)
  tagList(
    box(width = 12, status = box_status, solidHeader = box_solidHeader, collapsible = T, title = paste0(box_title),
        selection_ui(id = ns("selection_output"), label1 = label1, label2 = label2),
        withSpinner(plot_ui(id = ns("plot_output"))),type = 1)
  )
}

#' UI ouput for a table that is generated by server-side processing
#' @param id Namespace identifier for the module
table_output_ui <- function(id){
  ns <- NS(id)
  tagList(
    DTOutput(ns("table"))
  )
}

#' Combined UI for a box containing 2 selection boxes and server-generated table UI output
#' @param id Namespace identifier for the module
#' @param box_title (character) A title string to be displayed in the box header
#' @param box_status (character) Predefined Rshiny string determining the colour of the box border and header
#' @param box_solidHeader (logical) Should the box be displayed with a solid header line?
#' @param label1 (character) Text to display above the first selection box
#' @param label2 (character) Text to display above the first selection box
table_with_selection_ui <- function(id, box_title = "", box_status = "warning", box_solidHeader = TRUE, label1 = "", label2 = ""){
  ns <- NS(id)
  tagList(
    box(width = 12, status = box_status, solidHeader = box_solidHeader, collapsible = T, title = paste0(box_title),
        selection_ui(ns("selection_output"),label1 = label1, label2 = label2),
        withSpinner(table_output_ui(ns("table_output")), type = 1)
    )
  )
}
